name: push
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-compose-action@v2
      - run: make ci
      - uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: pigchevalier/devops-for-developers-project-74:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_KEY }}

